### PR TITLE
add fathom tracking script

### PR DESCRIPTION
**Pull request by ubergesundheit**

### CODE REVIEW

**Comment by top-on** [comment]
@ubergesundheit
the `docs/index.html` is auto-generated by `scripts/03_map.py`.
I will need some web-dev-support to add the fathom script into future versions of index.html :-)

**Comment by ubergesundheit** [comment]
Ping @silberzwiebel @jahnique how is this done in COVID-19-NRW?

**Comment by silberzwiebel** [comment]
plotly [does not write a full html](https://github.com/codeformuenster/COVID-19-NRW/blob/5fb7e00e99c0ffc72330d8d362951f7945aa375f/plot_data.py#L174) and a static footer.html is manually [hacked together](https://github.com/codeformuenster/COVID-19-NRW/blob/5fb7e00e99c0ffc72330d8d362951f7945aa375f/plot_data.py#L182)

**Comment by ubergesundheit** [comment]
I've updated this PR:

- jinja2 is used as templating engine
- The template includes the fathom tracking script

@thor I've noticed CI does not execute the actual script which generates the map. Is this intentional?

**Comment by thor** [comment]
I'm not the user you were looking for, but that's an interesting map. Viel Glück! 

@ThorbenJensen :) https://github.com/codeformuenster/divi-map/pull/2#issuecomment-613293195

**Review by top-on — APPROVED** [review]
cheers!

**Pull request merged**
